# Generated by Django 5.1.3 on 2024-11-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "激活"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="手机号"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "激活"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                (
                    "percent",
                    models.IntegerField(help_text="0-100百分比", verbose_name="折扣"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PricePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.SmallIntegerField(
                        choices=[(1, "激活"), (0, "删除")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="手机号"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.administrator",
                        verbose_name="创建者",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.level",
                        verbose_name="级别",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
